package com.shojikai.jdbc.bigquery;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

import com.google.api.services.bigquery.Bigquery;
import com.google.api.services.bigquery.model.QueryRequest;
import com.google.api.services.bigquery.model.QueryResponse;

public class BQStatement implements Statement {

	private Bigquery bq;
	private String projectId;
	private String datasetId;

	public BQStatement(Bigquery bq, String projectId, String datasetId) throws SQLException {
		this.bq = bq;
		this.projectId = projectId;
		this.datasetId = datasetId;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		throw new SQLException("Method not supported");
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		throw new SQLException("Method not supported");
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		try {
			QueryRequest req = new QueryRequest();
			req.setQuery(sql);
			QueryResponse res = bq.jobs().query(projectId, req).execute();
			return new BQResultSet(res);
		} catch (IOException e) {
			throw new SQLException("Something went wrong with the query: " + sql,e);
		}
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void close() throws SQLException {
		throw new SQLException("Method not supported");
	}

	@Override
	public int getMaxFieldSize() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setMaxFieldSize(int max) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int getMaxRows() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setMaxRows(int max) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setEscapeProcessing(boolean enable) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int getQueryTimeout() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void cancel() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void clearWarnings() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setCursorName(String name) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int getUpdateCount() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setFetchDirection(int direction) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int getFetchDirection() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setFetchSize(int rows) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int getFetchSize() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int getResultSetType() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void addBatch(String sql) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void clearBatch() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int[] executeBatch() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public Connection getConnection() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public boolean getMoreResults(int current) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys)
			throws SQLException {
		throw new SQLException("Method not supported");      
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes)
			throws SQLException {
		throw new SQLException("Method not supported");      
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames)
			throws SQLException {
		throw new SQLException("Method not supported");      
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys)
			throws SQLException {
		throw new SQLException("Method not supported");      
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public boolean execute(String sql, String[] columnNames)
			throws SQLException {
		throw new SQLException("Method not supported");      
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public boolean isClosed() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void setPoolable(boolean poolable) throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public boolean isPoolable() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public void closeOnCompletion() throws SQLException {
		throw new SQLException("Method not supported");    
	}

	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		throw new SQLException("Method not supported");    
	}

}
